/** National dex #1–#56 English names (Bulbasaur … Mankey). */
export const NATIONAL_DEX_NAMES_1_56 = [
  "Bulbasaur",
  "Ivysaur",
  "Venusaur",
  "Charmander",
  "Charmeleon",
  "Charizard",
  "Squirtle",
  "Wartortle",
  "Blastoise",
  "Caterpie",
  "Metapod",
  "Butterfree",
  "Weedle",
  "Kakuna",
  "Beedrill",
  "Pidgey",
  "Pidgeotto",
  "Pidgeot",
  "Rattata",
  "Raticate",
  "Spearow",
  "Fearow",
  "Ekans",
  "Arbok",
  "Pikachu",
  "Raichu",
  "Sandshrew",
  "Sandslash",
  "Nidoran♀",
  "Nidorina",
  "Nidoqueen",
  "Nidoran♂",
  "Nidorino",
  "Nidoking",
  "Clefairy",
  "Clefable",
  "Vulpix",
  "Ninetales",
  "Jigglypuff",
  "Wigglytuff",
  "Zubat",
  "Golbat",
  "Oddish",
  "Gloom",
  "Vileplume",
  "Paras",
  "Parasect",
  "Venonat",
  "Venomoth",
  "Diglett",
  "Dugtrio",
  "Meowth",
  "Persian",
  "Psyduck",
  "Golduck",
  "Mankey",
];

export const CANONICAL_TYPE_NAMES = new Set([
  "Normal",
  "Fire",
  "Water",
  "Electric",
  "Grass",
  "Ice",
  "Fighting",
  "Poison",
  "Ground",
  "Flying",
  "Psychic",
  "Bug",
  "Rock",
  "Ghost",
  "Dragon",
  "Dark",
  "Steel",
  "Fairy",
]);

/** Spot-check entries referenced in spec E2E. */
export const SPOT_CHECK_DEX = {
  1: { name: "Bulbasaur", types: ["Grass", "Poison"] },
  25: { name: "Pikachu", types: ["Electric"] },
  56: { name: "Mankey", types: ["Fighting"] },
};

export const REQUIRED_POKEMON_KEYS = [
  "nationalDexNumber",
  "name",
  "weight",
  "height",
  "types",
  "spriteNormal",
  "spriteShiny",
];
